version: "2"
linters:
  settings:
    depguard:
      rules:
        main:
          allow:
            - bytes
            - context
            - crypto
            - encoding
            - errors
            - fmt
            - log
            - net
            - github.com/drathveloper/go-cloud-gateway
            - github.com/go-playground/validator/v10
            - golang.org/x/net/http2
            - gopkg.in/yaml.v3
            - io
            - reflect
            - regexp
            - slices
            - strconv
            - strings
            - sync
            - testing
            - time
    govet:
      enable-all: true
  default: all
  disable:
    - revive
    - wsl
    - tagliatelle
    - tagalign
    - nlreturn
    - exhaustruct
    - ireturn
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - varnamelen
          - paralleltest
          - mirror
          - lll
          - funlen
          - forcetypeassert
          - gochecknoglobals
          - err113
          - dupl
          - maintidx
      - linters:
          - gosec
        text: 'G104:'
      - linters:
          - revive
        text: 'package-comments:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - k8s.io/kube-state-metrics
        - k8s.io/kube-state-metrics/v2
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
